-- 1. Ý nghĩa: Phục vụ cho chức năng chuyển chi nhánh
-- 2. Cú pháp:
CREATE PROCEDURE sp_chuyenChiNhanh
@MANV INT,
@MACN nchar(10)
AS
DECLARE @LGNAME VARCHAR(50)
DECLARE @USERNAME VARCHAR(50)
SET XACT_ABORT ON;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
	BEGIN DISTRIBUTED TRANSACTION
		DECLARE @HO NVARCHAR(40)
		DECLARE @TEN NVARCHAR(10)
		DECLARE @SOCMND NVARCHAR(20)
		DECLARE @DIACHI NVARCHAR(100)
		DECLARE @NGAYSINH DATETIME
		DECLARE @LUONG FLOAT

		SELECT @HO = HO, @TEN = TEN, @SOCMND = SOCMND, @DIACHI = DIACHI, @NGAYSINH = NGAYSINH, @LUONG = LUONG FROM NhanVien WHERE MANV = @MANV
		
		IF EXISTS (SELECT MANV FROM LINK1.QLVT.DBO.NhanVien WHERE HO = @HO
																AND TEN = @TEN
																AND SOCMND = @SOCMND
																AND DIACHI = @DIACHI
																AND NGAYSINH = @NGAYSINH
																AND LUONG = @LUONG)
			BEGIN
				UPDATE LINK1.QLVT.DBO.NhanVien
				SET TrangThaiXoa = 0
				WHERE HO = @HO
					AND TEN = @TEN
					AND SOCMND = @SOCMND
					AND DIACHI = @DIACHI
					AND NGAYSINH = @NGAYSINH
					AND LUONG = @LUONG				
			END
		ELSE
			BEGIN
				INSERT INTO LINK1.QLVT.DBO.NhanVien(MANV, HO, TEN, SOCMND, DIACHI, NGAYSINH, LUONG, MACN, TrangThaiXoa) 
							VALUES((SELECT MAX(MANV) FROM LINK0.QLVT.DBO.NhanVien) + 1, @HO, @TEN, @SOCMND, @DIACHI, @NGAYSINH, @LUONG, @MACN, 0)
			END
		UPDATE DBO.NhanVien
		SET TrangThaiXoa = 1
		WHERE MANV = @MANV
	COMMIT TRAN;
	IF EXISTS(SELECT SUSER_SNAME(sid) FROM sys.sysusers WHERE name = CAST(@MANV AS NVARCHAR))
		BEGIN
			SET @LGNAME = CAST((SELECT SUSER_SNAME(sid) FROM sys.sysusers WHERE name = CAST(@MANV AS NVARCHAR)) AS VARCHAR(50))
			SET @USERNAME = CAST(@MANV AS VARCHAR(50))
			EXEC SP_DROPUSER @USERNAME;
			EXEC SP_DROPLOGIN @LGNAME;
		END	
END

-- 3. Cú pháp kiểm tra:
EXEC sp_chuyenChiNhanh 11, 'CN2'