USE [QLVT]
GO
/****** Object:  StoredProcedure [dbo].[sp_hoatDongCuaNhanVien]    Script Date: 27/08/2023 12:22:02 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[sp_hoatDongCuaNhanVien]
@MANV INT,
@DATEFROM DATETIME,
@DATETO DATETIME
AS
BEGIN
	SELECT FORMAT(NGAY, 'MM-yyyy') AS THANG, pn.NGAY, pn.MAPN, N'Nhập' AS LOAIPHIEU, '' AS KHACHHANG,TENVT, SOLUONG, DONGIA, (SOLUONG*DONGIA) AS TRIGIA
	FROM (SELECT MAPN, MANV, NGAY FROM PhieuNhap WHERE (NGAY BETWEEN @DATEFROM AND @DATETO) AND (MANV = @MANV)) pn,
		(SELECT MAPN, MAVT, SOLUONG, DONGIA FROM CTPN) ctpn,
		(SELECT MAVT, TENVT FROM Vattu) vt
	WHERE pn.MAPN = ctpn.MAPN AND ctpn.MAVT = vt.MAVT 
	GROUP BY pn.NGAY, pn.MAPN, TENVT, SOLUONG, DONGIA
	UNION ALL
	SELECT FORMAT(NGAY, 'MM-yyyy') AS THANG, px.NGAY, px.MaPX, N'Xuất' AS LOAIPHIEU, px.HOTENKH AS KHACHHANG, TENVT, SOLUONG, DONGIA, (SOLUONG*DONGIA) AS TRIGIA
	FROM (SELECT MAPX, HOTENKH, MANV, NGAY FROM PhieuXuat WHERE (NGAY BETWEEN @DATEFROM AND @DATETO) AND (MANV = @MANV)) px,
		(SELECT MAPX, MAVT, SOLUONG, DONGIA FROM CTPX) ctpx,
		(SELECT MAVT, TENVT FROM Vattu) vt
	WHERE px.MAPX = ctpx.MAPX AND ctpx.MAVT = vt.MAVT
	GROUP BY px.NGAY, px.MAPX,px.HOTENKH, TENVT, SOLUONG, DONGIA
END
GO